from __future__ import annotations

import base64
import csv
import io
from datetime import datetime, timedelta, timezone

from analytics import (
    get_history,
    get_today_summary,
    get_weekly_summary,
    get_monthly_summary,
    format_timestamp_for_display,
    _filter_meaningful_records,
)


def build_report_range(range_name: str):
    now = datetime.now(timezone.utc)
    if range_name == "today":
        start = now.replace(hour=0, minute=0, second=0, microsecond=0)
        end = start + timedelta(days=1)
    elif range_name == "weekly":
        start = now - timedelta(days=7)
        end = now
    elif range_name == "monthly":
        start = now - timedelta(days=30)
        end = now
    else:
        start = now - timedelta(days=30)
        end = now
    return start, end


def _get_range_records(range_name: str):
    start, end = build_report_range(range_name)
    return get_history(start_date=start.isoformat(), end_date=end.isoformat(), include_idle=False, limit=None)


def _build_summary_payload(range_name: str):
    if range_name == "today":
        return get_today_summary()
    if range_name == "weekly":
        return get_weekly_summary()
    if range_name == "monthly":
        return get_monthly_summary()
    return get_today_summary()


def _escape_pdf_text(text: str) -> str:
    return str(text).replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")


def build_pdf_report(range_name: str):
    try:
        payload = _build_summary_payload(range_name)
    except Exception as exc:
        raise ValueError("No data available for export.") from exc

    if payload.get("status") != "success":
        raise ValueError("No data available for export.")

    summary = payload.get("summary", {})
    charts = payload.get("charts", {})
    # generated_at should be shown in Asia/Kolkata local time with required format
    generated_at = format_timestamp_for_display(datetime.now(timezone.utc))

    records = _get_range_records(range_name)
    summary_lines = [
        "AI-Based Smart Traffic Congestion Optimization System",
        "",
        f"Project Name: AI Traffic Control System",
        f"Generated Date: {generated_at}",
        f"Selected Range: {range_name.title()}",
        "",
        "Summary Table",
        f"Total Vehicles: {summary.get('totalVehicles', 0)}",
        f"Average Vehicles: {summary.get('averageVehicles', 0)}",
        f"Peak Hour: {summary.get('peakTrafficHour', 'N/A')}",
        f"Highest Traffic Road: {summary.get('highestTrafficRoad', 'N/A')}",
        f"Least Busy Road: {summary.get('leastBusyRoad', 'N/A')}",
        f"Average Waiting Time: {summary.get('averageWaitingTime', 0)}",
        f"Highest Density: {summary.get('highestDensity', 'LOW')}",
        "",
        "Traffic Statistics Table",
    ]

    for item in charts.get("roadDistribution", [])[:10]:
        summary_lines.append(f"- {item.get('road', 'N/A')}: {item.get('vehicles', 0)} vehicles")

    summary_lines.extend(["", "Generated by", "AI-Based Smart Traffic Congestion Optimization System"])

    if not records:
        summary_lines.append("")
        summary_lines.append("No meaningful traffic activity available for export.")

    content_parts = []
    for index, line in enumerate(summary_lines):
        y_position = 760 - (index * 14)
        content_parts.append(f"BT /F1 12 Tf 50 {y_position} Td ({_escape_pdf_text(line)}) Tj ET")

    content_stream = "\n".join(content_parts)
    content_bytes = content_stream.encode("latin-1", "replace")
    content_length = len(content_bytes)

    objects = [
        "1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n",
        "2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n",
        "3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>\nendobj\n",
        f"4 0 obj\n<< /Length {content_length} >>\nstream\n{content_stream}\nendstream\nendobj\n",
        "5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n",
    ]

    pdf_bytes = bytearray(b"%PDF-1.4\n")
    offsets = [0]
    for obj in objects:
        offsets.append(len(pdf_bytes))
        pdf_bytes.extend(obj.encode("latin-1"))

    xref_offset = len(pdf_bytes)
    pdf_bytes.extend(b"xref\n0 6\n0000000000 65535 f \n")
    for offset in offsets[1:]:
        pdf_bytes.extend(f"{offset:010d} 00000 n \n".encode("ascii"))
    pdf_bytes.extend(b"trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n")
    pdf_bytes.extend(str(xref_offset).encode("ascii"))
    pdf_bytes.extend(b"\n%%EOF")
    return base64.b64encode(pdf_bytes).decode("ascii")


def build_csv_report(range_name="today", records=None):
    if records is None:
        try:
            payload = _build_summary_payload(range_name)
        except Exception as exc:
            raise ValueError("No data available for export.") from exc

        if payload.get("status") != "success":
            raise ValueError("No data available for export.")

        records = _get_range_records(range_name)
    else:
        records = _filter_meaningful_records(records)

    output = io.StringIO()
    writer = csv.writer(output)

    writer.writerow([
        "Timestamp",
        "Road",
        "Vehicle Count",
        "Density",
        "Signal Status",
        "Waiting Time",
        "Recommended Green Time",
        "Prediction"
    ])

    records = sorted(
        records,
        key=lambda r: r.get("timestamp") or datetime.min.replace(tzinfo=timezone.utc),
        reverse=True,
    )

    for record in records:
        prediction_status = str(record.get("prediction_status", "")).strip().lower()
        if prediction_status == "success" and record.get("predicted_vehicle_count") is not None:
            prediction_value = str(record.get("predicted_vehicle_count"))
        else:
            prediction_value = record.get("prediction")
            if not prediction_value or str(prediction_value).strip().lower() in {"unknown", "no video", "no_video", ""}:
                prediction_value = "unknown"

        writer.writerow([
            format_timestamp_for_display(record.get("timestamp")),
            record.get("road_name") or f"Road {record.get('road_id', '')}",
            record.get("vehicle_count", 0),
            record.get("density_level", "LOW"),
            record.get("signal_status", "UNKNOWN"),
            record.get("waiting_time", 0),
            record.get("recommended_green_time", 0),
            prediction_value,
        ])

    return output.getvalue()